name: 'Mostrar Mensaje'
description: 'Una acción que devuelve un mensaje.'
inputs: {}
outputs:
  message:
    description: 'El mensaje generado por la acción'
    # No es necesario poner 'value' en la definición de outputs para acciones de tipo composite

runs:
  using: 'composite'
  steps:
    - id: create_message
      name: Generate Message
      run: echo "La acción tiene un coche rojo" # Nota: No necesitas "::set-output" en acciones de tipo composite
      shell: bash # Asegúrate de especificar el shell si estás usando comandos en bash
