name: 'Mostrar Mensaje'
description: 'Una acción que devuelve un mensaje.'
inputs: {}
outputs:
  message:
    description: 'El mensaje generado por la acción'

runs:
  using: 'composite'
  steps:
    - id: generate_message
      name: Generate Message
      run: echo "message=La acción tiene un coche rojo" >> $GITHUB_ENV
      shell: bash
