name: 'Mostrar Autor del Último Commit'
description: 'Imprime el nombre del autor del último commit en los logs.'
runs:
  using: 'composite'
  steps:
    - name: Obtener el autor del último commit
      shell: bash
      run: |
        echo "El autor del último commit es: $(git log -1 --pretty=format:'%an')"
