name: Imprimir información sobre el runner

on:
  workflow_dispatch:

jobs:
  info_runner:
    runs-on: ubuntu-latest

    steps:
      
      - name: Imprimir nombre del sistema operativo
        run: |
          echo "Sistema operativo: ${{ runner.os }}"

      - name: Imprimir arquitectura del runner
        run: |
          echo "Arquitectura: ${{ runner.arch }}"
