name: Workflow manual con input seleccion

on: 
  workflow_dispatch:
    inputs:
      entorno:
        description: 'Selecciona un entorno'
        required: true
        type: choice
        options:
          - production
          - staging 

jobs:
  imprimir_entorno:
    runs-on: ubuntu-latest

    steps:
    - name: Imprimir entorno
      run: echo " ${{ github.event.inputs.entorno }} "
