name: Workflow manual con input confirmacion

on: 
    workflow_dispatch:
      inputs:
        confirmar:
          description: '¿Quieres proceder?'
          type: choice
          options:
            - yes
            - no

jobs: 
  confirm_job:
    runs-on: ubuntu-latest

    steps:
    - name: Check confirmation
      run: |
        if [ "${{ github.event.inputs.confirmar }}" == "true" ]; then
          echo "Perfecto, confirmacion recibida."
        else
          echo "No se procederá entonces."
        fi
