name: ejercicio2

on:
  workflow_dispatch:

jobs:
  definir_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Declarar variable
        id: set_output
        run: echo "::set-output name=var_step_output::valor"

      - name: Imprimir variable
        run: echo "The value of var_step_output is ${{ steps.set_output.outputs.var_step_output }}"