name: Configurar un workflow con dos Jobs (2)

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Show date and time
      run: date

    - name: Simulación de un fallo
      run: 
        echo "Simulacion de fallo desactivado"
        #exit 1


  deploy:
      runs-on: ubuntu-latest
      needs: build  

      steps:
      - name: Deployment Step
        run: echo "Deploying the application..."
      