name: Configurar un workflow con dos Jobs (4)

on:
  workflow_dispatch:

jobs:
  crear_archivo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "This is a test file." > test.txt

  move_file:
    runs-on: ubuntu-latest
    needs: crear_archivo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Move the text file
      run: |
        mkdir -p new_directory 
        mv test.txt new_directory/  

#Al ejecutar el workflow, cuando el segundo job se ejecuta, intenta mover test.txt
# sin embargo, el job  no encontrará el archivo test.txt porque no existe en 
# en su entorno de ejecución y resultará en un error que indica que el archivo no se encuentra
#Esto se debe a que los jobs de github acitons se ejecutan en entornos separados
