name: Configurar un workflow con dos Jobs BIEN (4.2)

on:
  workflow_dispatch:

jobs:
  create_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "This is a test file." > test.txt

    - name: Upload test.txt
      uses: actions/upload-artifact@v3 
      with:
        name: test-file
        path: test.txt

  move_file:
    runs-on: ubuntu-latest
    needs: create_file

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download test.txt
      uses: actions/download-artifact@v3
      with:
        name: test-file

    - name: Move the text file
      run: |
        mkdir -p new_directory
        mv test.txt new_directory/
