name: Flujo de Trabajo Básico

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Imprimir Hola Mundo
      run: echo Hola, mundo!
