name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      image_name: ${{ steps.docker_build.outputs.image_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Docker image
        id: docker_build
        uses: stemdo-labs/actions/build-and-push-docker-image@main
        with:
          registry_url: 'docker.io'
          repository: 'ploopez/prueba'
          tag: 'latest'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: '.'

      - name: Print Image input (extract version)
        run: echo "La version que se va a taggear es ${{ steps.docker_build.outputs.image_name }}"
