{
  "scheme": "semantic",
  
  // file where the current version can be found
  "versionFile": "./package.json", 
  "files": [
    {
      "path": // path to file containing version to be updated
      "line": // optional line number if needed
    }
  ],
  "rules": [
    {
      "trigger": "commit",
      "branch": "hotfix",
      "bump": "build"
    },
    {
      "trigger": "commit",
      "bump": "minor",
      "branch": "master",
      "reset": "build"
    },
    {
      "trigger": "commit",
      "bump": "major",
      "branch": "release",
      "reset": [
        "minor",
        "build"
      ]
    }
  ]}
