name: Desplegar en Entorno Correspondiente

on:
  push:
    branches:
      - main
      - develop
      - release/*

  workflow_dispatch:  

jobs:
  determinar-entorno:
    runs-on: ubuntu-latest

    outputs:
      entorno: ${{ steps.set-entorno.outputs.entorno }}

    steps:
      - name: Determinar entorno de despliegue
        id: set-entorno
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            echo "production"
            echo "entorno=production" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == refs/heads/develop ]]; then
            echo "development"
            echo "entorno=development" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == refs/heads/release/* ]]; then
            echo "staging"
            echo "entorno=staging" >> $GITHUB_ENV
          else
            echo "Error: Rama desconocida para despliegue" && exit 1
          fi

          echo "entorno=${GITHUB_ENV}" >> $GITHUB_ENV

  desplegar:
    runs-on: ubuntu-latest
    needs: determinar-entorno

    environment: ${{ needs.determinar-entorno.outputs.entorno }}

    steps:
      - name: Obtener variables del entorno
        run: |
          echo "API_URL=${{ vars.API_URL }}"
          echo "LOG_LEVEL=${{ vars.LOG_LEVEL }}"

      - name: Imprimir entorno y variables
        run: |
          echo "Desplegando en el entorno ${{ needs.determinar-entorno.outputs.entorno }}"
          echo "API_URL=${{ vars.API_URL }}"
          echo "LOG_LEVEL=${{ vars.LOG_LEVEL }}"

      - name: Simular despliegue
        run: |
          echo "Desplegando con API_URL=${{ vars.API_URL }} y LOG_LEVEL=${{ vars.LOG_LEVEL }}"
