name: Validar Branch

on:
  workflow_call:
    inputs:
      tarea_principal:
        description: 'La tarea principal a ejecutar'
        required: true
        type: string

jobs:
  validar_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Validar si la rama comienza con "feature/"
        run: |
          branch_name=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          if [[ "$branch_name" == feature/* ]]; then
            echo "La rama comienza con 'feature/'."
          else
            echo "Error: La rama no comienza con 'feature/'."
            exit 1
          fi

  ejecutar_tarea_principal:
    runs-on: ubuntu-latest
    needs: validar_branch
    if: success()  

    steps:
      - name: Ejecutar tarea principal
        run: |
          echo "${{ inputs.tarea_principal }}"
