name: Ejemplo de Uso de Acción Personalizada

on:
  workflow_call:

jobs:
  saludo_job:
    runs-on: ubuntu-latest
    name: Un job que usa la acción de saludo
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Saludo personalizado
      id: mi_saludo
      uses: ploopez/actions/.github/actions@main
      with:
        nombre: 'GitHub Actions'
    - name: Usar el saludo
      run: echo "El saludo fue '${{ steps.mi_saludo.outputs.saludo }}'"
