name: 3. Update Version (semantic versioning)

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'Path to the file containing the version'
        required: true
        default: 'package.json'
      version-key:
        description: 'The key to find the version in the file'
        required: true
        default: 'version'
      #bump-type:
      #  description: 'Type of version bump: major, minor, or patch'
      #  required: true
      #  default: 'patch'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update version
        uses: stemdo-labs/actions/semantic-versioning@main
        with:
          file: ${{ github.event.inputs.file }}
          version-key: ${{ github.event.inputs.version-key }}
          #bump-type: ${{ github.event.inputs.bump-type }}
