#name: Show Me the S3cr3tz
#on: [push]

#jobs:
#  debug:
#    name: Debug
#    runs-on: ubuntu-latest

#    steps:
#    - name: Check out code
#      uses: actions/checkout@v2

#    - name: Set up secret file
#      env:
#        DEBUG_PASSWORD: ${{ secrets.DOCKER_USERNAME }}
#        DEBUG_SECRET_KEY: ${{ secrets.DOCKER_PASSWORD }}
#      run: |
#        echo $DEBUG_PASSWORD >> secrets.txt
#        echo $DEBUG_SECRET_KEY >> secrets.txt

#    - name: Run tmate
#      uses: mxschmitt/action-tmate@v2

name: Show Secret Value

on:
  workflow_dispatch:
    inputs:
      secretName:
        description: 'Name of the secret to show'
        required: true

jobs:
  show-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Show secret value
        uses: stemdo-labs/actions/show-secret-value@show-secret-value
        with:
          secret_value: ${{ secrets[github.event.inputs.secretName] }}
