name: Push en develop y Hello World

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Saludo
      run: echo "Hello World"
    
