name: Sheduler

on:
  #workflow_dispatch: 
  schedule:
    - cron: '00 12 * * *'

jobs:
  hora_e_impresion:
    runs-on: ubuntu-latest
    steps:
      - name: Show Current Time
        run: date

      - name: Imprimir mensaje
        run: echo "Scheduled job executed!"
